[metadata]
name = trustldm
version = 0.1.0
author = Yichuan Mo, Yanbo Shi, Yukun Jiang, Mingjie Li
author_email = shiyanbo@stu.pku.edu.cn
description = TrustLDM: Benchmarking Trustworthiness in Language Diffusion Models
long_description = TrustLDM is an evaluation suite for studying the trustworthiness of recent diffusion language models (LDMs). This is the static evaluation mode.
keywords = trustworthiness, diffusion language models, LDM, evaluation
license = Creative Commons Public Licenses
classifiers =
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.9
    License :: OSI Approved :: Apache Software License
url = https://github.com/mo666666/Trustworthy_DLLM

[options]
python_requires = >=3.10
packages = find:
zip_safe = False
include_package_data = True

install_requires =
    absl-py==2.3.1
    accelerate==1.10.1
    aiodns==3.5.0
    aiohappyeyeballs==2.6.1
    aiohttp==3.13.0
    aiohttp-retry==2.9.1
    aiosignal==1.4.0
    aleph-alpha-client==2.14.0
    anthropic==0.2.10
    antlr4-python3-runtime==4.9.3
    anyio==4.11.0
    async-timeout==5.0.1
    attrs==25.4.0
    blis==0.7.11
    bottle==0.12.25
    cachetools==6.2.1
    catalogue==2.0.10
    cattrs==22.2.0
    certifi==2025.10.5
    cffi==2.0.0
    charset-normalizer==3.4.4
    click==8.3.0
    cmake==4.1.0
    colorcet==3.0.1
    confection==0.1.5
    contourpy==1.3.2
    # crfm-helm @ file:///home1/ybshi/DecodingTrust-main/crfm_helm-0.2.3-py3-none-any.whl#sha256=538becea83d95f6784ff8781f33aaef5a019e746952f31900912edbc48c00e3f
    cycler==0.12.1
    cymem==2.0.11
    dacite==1.6.0
    datasets==2.16.1

    dill==0.3.5.1
    exceptiongroup==1.3.0
    fairlearn==0.9.0
    filelock==3.20.0
    fonttools==4.60.1
    frozenlist==1.8.0
    fsspec==2023.10.0
    google-api-core==2.26.0
    google-api-python-client==2.64.0
    google-auth==2.41.1
    google-auth-httplib2==0.2.0
    googleapis-common-protos==1.70.0
    h11==0.16.0
    hf-xet==1.1.10
    httpcore==1.0.9
    httplib2==0.31.0
    httpx==0.28.1
    huggingface-hub==0.36.0
    hydra-core==1.3.2
    icetk==0.0.4
    idna==3.11
    importlib-resources==5.10.4
    Jinja2==3.1.6
    joblib==1.5.2
    jsonlines==3.1.0
    kiwisolver==1.4.9
    langcodes==3.5.0
    language_data==1.3.0
    lit==18.1.8
    Mako==1.2.4
    marisa-trie==1.3.1
    MarkupSafe==3.0.3
    matplotlib==3.6.3
    mpmath==1.3.0
    multidict==6.7.0
    multiprocess==0.70.13
    murmurhash==1.0.13
    networkx==3.4.2
    nltk==3.9.2
    numpy==1.24.3
    omegaconf==2.3.0
    openai==0.27.10
    packaging==25.0
    pandas==2.3.3
    param==2.2.1
    parameterized==0.9.0
    pathlib_abc==0.1.1
    pathy==0.11.0
    pillow==12.0.0
    preshed==3.0.10
    propcache==0.4.1
    proto-plus==1.26.1
    protobuf==3.20.3
    psutil==7.1.0
    pyarrow==14.0.2
    pyarrow-hotfix==0.7
    pyasn1==0.6.1
    pyasn1_modules==0.4.2
    pycares==4.11.0
    pycparser==2.23
    pyct==0.6.0
    pydantic==1.10.24
    pyext==0.7
    pyhocon==0.3.61
    pymongo==4.2.0
    pyparsing==3.2.5
    python-dateutil==2.9.0.post0
    pytz==2025.2
    PyYAML==6.0.3
    regex==2025.10.23
    requests==2.32.5
    responses==0.18.0
    retrying==1.3.7
    rouge_score==0.1.2
    rsa==4.9.1
    safetensors==0.6.2
    scikit-learn==1.7.2
    scipy==1.15.3
    seaborn==0.11.2
    sentencepiece==0.1.99
    shortuuid==1.0.13
    simple-slurm==0.2.7
    six==1.17.0
    smart-open==6.4.0
    sniffio==1.3.1
    spacy==3.5.4
    spacy-legacy==3.0.12
    spacy-loggers==1.0.5
    sqlitedict==1.7.0
    srsly==2.5.1
    sympy==1.14.0
    tenacity==8.2.3
    thinc==8.1.12
    threadpoolctl==3.6.0
    tiktoken==0.3.3
    tokenizers==0.19.1
    tqdm==4.67.1
    transformers==4.43.2
    triton==2.0.0
    typer==0.9.4
    typing_extensions==4.15.0
    tzdata==2025.2
    uncertainty-calibration==0.1.4
    uritemplate==4.2.0
    urllib3==2.5.0
    wasabi==1.1.3
    websocket-client==1.3.3
    xxhash==3.6.0
    yarl==1.22.0
    zstandard==0.18.0


[options.extras_require]

awq =
    crfm-helm[awq] @ git+https://github.com/danielz02/helm.git@main

gptq =
    crfm-helm[gptq] @ git+https://github.com/danielz02/helm.git@main

quant =
    crfm-helm[quant] @ git+https://github.com/danielz02/helm.git@main

slurm =
    hydra-submitit-launcher~=1.2.0
    submitit~=1.5.0

all =
    trustldm[quant]
    trustldm[slurm]

[options.entry_points]
console_scripts =
    trustldm-stat = trustldm_static.main:main

[options.packages.find]
where = .
exclude =
    tests*

# Settings for Flake8: Tool For Style Guide Enforcement
[flake8]
max-line-length = 120
exclude = venv/*

# Ignore completely:
# E203 - White space before ':', (conflicts with black)
# E231 - Missing whitespace after ',', ';', or ':'
# E731 - do not assign a lambda expression, use a def
# W503 - line break before binary operator, (conflicts with black)
# W605 - invalid escape sequence '\', (causes failures)
ignore = E203,E231,E731,W503,W605

# Settings for Mypy: static type checker for Python 3
[mypy]
ignore_missing_imports = True

[tool:pytest]
addopts =
    # By default, we don't test models because doing so will
    # make real requests and spend real money
    -m 'not models'
markers =
    # Marker for tests that make real model requests
    models
