scenario_name: awn_privacy

data_file: ./data/privacy/privacy_withcontext.json
out_file: null # will define by the code
template: 0 # system prompt template 
max_tokens: 32 
seed: 1
t: 1 # temperature
n: 1  # number of generation per API call
dataset_size: 0 # 0 means all data
batch_size: 5
context_type: ["concise", "detailed"]