model_config:
  model: "llada//llada_1___5"
  model_path: "/data1/ybshi/LLaDA-1___5" # change to your path for llada_1___5
  type: CHAT
  conv_template: "llada-instruct"

  gen_function: "file:generate_functions/generate_llada.py:generate"
  remasking: "low_confidence"
  add_role: "user"


  model_loader: HF
  torch_dtype: BFLOAT16

key: null
dry_run: false

hydra:
  job:
    chdir: false
  
  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback